insert into fu_defaults (fu_type,fu_columnIndex,fu_columnType,fu_columnTitle,fu_property,fu_default,fu_picker)
values

('VoiceMail','2','editTextNoEditColumn','Number',NULL,'',NULL),
('VoiceMail','3','editTextColumn','Password',NULL,'1234',NULL),
('VoiceMail','4','dropdownColumn','Can Record',"['yes','no']",'yes',NULL),
('VoiceMail','5','editTextColumn','Max Messages',NULL,'60',NULL),
('VoiceMail','6','editTextColumn','Message Length',NULL,'200',NULL),
('VoiceMail','7','pickerColumn','Default Email',NULL,NULL,'createVoiceEmailPicker'),
('VoiceMail','8','dropdownColumn','Inculde Mp3 In Email',"['yes','no']",'no',NULL),
('VoiceMail','9','editColumn',NULL,NULL,'',NULL),
('VoiceMail','10','deleteColumn',NULL,NULL,'',NULL),
('Extension','1','idColumn',NULL,NULL,'',NULL),
('Extension','2','editTextNoEditColumn',NULL,NULL,'',NULL),
('Extension','3','editTextColumn','Password',NULL,'1234',NULL),
('Extension','4','ajaxDropdownColumn',NULL,'"/DDI/AvailableDDIs"','',NULL),
('Extension','6','editTextColumn',NULL,NULL,'',NULL),
('Extension','7','editTextColumn',NULL,NULL,'',NULL),
('Extension','8','editTextColumn',NULL,NULL,'',NULL),
('Extension','9','editTextColumn',NULL,NULL,'',NULL),
('Extension','10','editTextColumn',NULL,NULL,'',NULL),
('Extension','12','ajaxDropdownColumn',NULL,'"/VoiceMail/AvailableVoiceMails"','',NULL),
('Extension','13','editTextColumn','Mail Delay',NULL,'0',NULL),
('Extension','16','nonEditColumn',NULL,NULL,'',NULL),
('Extension','17','nonEditColumn',NULL,NULL,'',NULL),
('Extension','18','nonEditColumn',NULL,NULL,'',NULL),
('Extension','19','editColumn',NULL,NULL,'',NULL),
('Extension','20','deleteColumn',NULL,NULL,'',NULL),
('Queue','1','idColumn',NULL,NULL,'',NULL),
('Queue','2','editTextNoEditColumn',NULL,NULL,'',NULL),
('Queue','3','editTextColumn',NULL,NULL,'',NULL),
('Queue','4','editTextColumn',NULL,NULL,'',NULL),
('Queue','5','nonEditColumn',NULL,NULL,'',NULL),
('Queue','6','dropdownColumn','Type',"['ring all', 'least recent', 'fewest calls', 'random', 'round robin', 'linear', 'weighted random']",'ring all',NULL),
('Queue','7','dropdownColumn','Ring On Busy',"['yes', 'no']",'yes',NULL),
('Queue','8','ajaxDropdownColumn',NULL,'"/VoiceMail/AvailableVoiceMails"','',NULL),
('Queue','9','editTextColumn','Mail delay',NULL,'0',NULL),
('Queue','12','linkColumn',NULL,NULL,'',NULL),
('Queue','13','editColumn',NULL,NULL,'',NULL),
('Queue','14','deleteColumn',NULL,NULL,'',NULL),
('Route','1','idColumn',NULL,NULL,'',NULL),
('Route','2','dropdownColumn','Ring plan','[]','default',NULL),
('Route','3','pickerColumn',NULL,NULL,NULL,'createNumberPicker'),
('Route','4','editTextColumn','Order',NULL,'0',NULL),
('Route','5','pickerColumn',NULL,NULL,'','createRouteToPicker'),
('Route','6','editTextColumn','Ring Time',NULL,'10',NULL),
('Route','7','editColumn',NULL,NULL,NULL,NULL),
('Route','8','deleteColumn',NULL,NULL,'',NULL),
('VoiceMail','1','idColumn',NULL,NULL,'',NULL),
('Extension','5','ajaxDropdownColumn',NULL,'"/CLI/CLINumberData"','',NULL),
('VoiceMessages','0',NULL,'Recycle Time in Days',NULL,'30',NULL),
('Extension','11','ajaxDropdownColumn',NULL,'"/PermissionClass/AvailablePermissions"','',NULL),
('Queue','10','ajaxDropdownColumn',NULL,'"/MusicOnHold/AvailableMoh"','',NULL),
('Extension','14','dropdownColumn',NULL,"['user', 'admin','trunk']",'user',NULL),
('Extension','15','dropdownColumn',NULL,"['exclude','include']",'include',NULL),
('Queue','11','dropdownColumn',NULL,"['exclude','include']",'include',NULL)