//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsteriskCTIClient.GetComapnyDetails {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GetComapnyDetails.ICompanyDetail")]
    public interface ICompanyDetail {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompanyDetail/GetCompanyFromNumber", ReplyAction="http://tempuri.org/ICompanyDetail/GetCompanyFromNumberResponse")]
        string GetCompanyFromNumber(string value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICompanyDetailChannel : AsteriskCTIClient.GetComapnyDetails.ICompanyDetail, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CompanyDetailClient : System.ServiceModel.ClientBase<AsteriskCTIClient.GetComapnyDetails.ICompanyDetail>, AsteriskCTIClient.GetComapnyDetails.ICompanyDetail {
        
        public CompanyDetailClient() {
        }
        
        public CompanyDetailClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CompanyDetailClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CompanyDetailClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CompanyDetailClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetCompanyFromNumber(string value) {
            return base.Channel.GetCompanyFromNumber(value);
        }
    }
}
